### ISSUE TITLE
/index.php/api/xmlrpc: 404 Not Found

### ISSUE THREAD

**Issue by dschiller** [fulfilio/python-magento#24]
Using Magento 2.2.5 the following Code:

```
import magento

url = 'https://www.myWebsite.de'
apiuser = 'api'
apipass = '***'

# Create an instance of API
client = magento.API(url, apiuser, apipass)

# Get a list of product types
product_types = client.product_types.list()

print(product_types)
```

results in:

```
D:\Work\Coding\AmCa\MagentoAPI>showProducts.py
Traceback (most recent call last):
  File "D:\Work\Coding\AmCa\MagentoAPI\showProducts.py", line 11, in <module>
    product_types = client.product_types.list()
  File "C:\Program Files\Python37\lib\site-packages\magento\api.py", line 54, in <lambda>
    property(lambda self: self.get_instance_of(Klass))
  File "C:\Program Files\Python37\lib\site-packages\magento\api.py", line 239, in get_instance_of
    self.__dict__[Klass.__name__] = value.__enter__()
  File "C:\Program Files\Python37\lib\site-packages\magento\api.py", line 177, in __enter__
    self.username, self.password)
  File "C:\Program Files\Python37\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files\Python37\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Program Files\Python37\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files\Python37\lib\xmlrpc\client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for www.myWebsite.de/index.php/api/xmlrpc: 404 Not Found>
```

**Comment by iamprayush** [comment]
I'm getting a similar error with a 302 instead of a 404:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.8/site-packages/magento/api.py", line 54, in <lambda>
    property(lambda self: self.get_instance_of(Klass))
  File "/venv/lib/python3.8/site-packages/magento/api.py", line 239, in get_instance_of
    self.__dict__[Klass.__name__] = value.__enter__()
  File "/venv/lib/python3.8/site-packages/magento/api.py", line 176, in __enter__
    self.session = self.client.login(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1183, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for myWebsite.com/index.php/api/xmlrpc: 302 Found>
```

**Comment by tburton12** [comment]
Did anyone resolve this issue?

**Comment by dschiller** [comment]
I could not. I was expecting someone could help but it seems it's not common. I believe the project is dead.

**Comment by tburton12** [comment]
I realized that the part which is missing, the xmlrpc, is related to the protocol also called XML-RPC. This is what this project uses for sending requests. Xml-rpc is no longer supported in newer Magento releases. I think this repo is outdated for those.
Correct me if I'm wrong

**Comment by dschiller** [comment]
I found this article from January last year: https://zapier.com/help/doc/common-problems-magento
I am not sure if XML RPC is deprecated. Where did you read about that XML-RPC is not longer supported in newer Magento releases ?

**Comment by dschiller** [comment]
You are right, it is no longer supported: https://alanstorm.com/magento-2-understanding-the-web-api-architecture

Guess we can close this one and leave.
